// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKCBrDlvq0lsGyEYWbnuS1iCxT_ePruQY',
    appId: '1:321435976541:web:3aa3a98b3fc9e393969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    authDomain: 'inventory-management-flutter.firebaseapp.com',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    measurementId: 'G-SS6J410EYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUil11iAxKlywKk8T4EZ6Zmx3oPaI95Ek',
    appId: '1:321435976541:android:ef41b8bc1ac053de969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxo2MUThNbZl1n3eNd-MZjy0z3DYERNP4',
    appId: '1:321435976541:ios:29730dfa1a18fc95969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    iosBundleId: 'com.example.cw06Assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxo2MUThNbZl1n3eNd-MZjy0z3DYERNP4',
    appId: '1:321435976541:ios:29730dfa1a18fc95969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    iosBundleId: 'com.example.cw06Assignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKCBrDlvq0lsGyEYWbnuS1iCxT_ePruQY',
    appId: '1:321435976541:web:be4d3c5cc7a8b4cc969eb4',
    messagingSenderId: '321435976541',
    projectId: 'inventory-management-flutter',
    authDomain: 'inventory-management-flutter.firebaseapp.com',
    storageBucket: 'inventory-management-flutter.firebasestorage.app',
    measurementId: 'G-3C6GM29XFY',
  );
}
